version: '3.8'

services:
  app:
    image: postgres/horizon_hotel:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/horizon_hotel
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 654832
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: horizon_hotel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 654832
    ports:
      - "5432:5432"